version: '3.8'

services:

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000" # Replace with the port your app listens on
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: database
      JWT_TOKEN_PASSPHRASE: mysecretpassphrase
      REDIS_URL: redis://redis:6379
      REDIS_SSL_MODE: off
      DATABASE_SSL_MODE: off
    depends_on:
      - database
      - redis